[build]
builder = "nixpacks"
buildCommand = "npm install && npx expo export"

[deploy]
numReplicas = 1
restartPolicyType = "always"
sleepApplication = false
startCommand = "npm run serve"

[nixpacks]
installCommand = "npm install"

[service]
autoDeploy = true
healthcheckPath = "/"
healthcheckTimeout = 300
port = 8080