[build]
builder = "nixpacks"
buildCommand = "npm install && npx expo export && echo 'Cache busted'"

[deploy]
numReplicas = 1
restartPolicyType = "always"
sleepApplication = false
startCommand = "npx serve -s dist -l 8081"

[nixpacks]
installCommand = "npm install"

[service]
autoDeploy = true
healthcheckPath = "/"
healthcheckTimeout = 300
port = 8081