[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && npm install && node src/server.js"
healthcheckPath = "/"
healthcheckTimeout = 180
restartPolicyType = "always"

[nixpacks]
nodejs = "18"