[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "cd backend && npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "always"

[nixpacks]
nodejs = "18"