name: kodo
regions:
- sfo
services:
- dockerfile_path: server.Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: your-github-username/kodo
  health_check:
    http_path: /health
  http_port: 3001
  instance_count: 1
  instance_size_slug: basic-xs
  name: kodo-server
  routes:
  - path: /api
  source_dir: /
databases:
- engine: REDIS
  name: kodo-redis
  production: false
  version: "6"
  cluster_size: basic-xs
  db_name: kodo
  db_user: kodo
envs:
- key: OPENAI_API_KEY
  scope: RUN_TIME
  value: "${OPENAI_API_KEY}"
- key: NODE_ENV
  scope: RUN_TIME
  value: production
- key: PORT
  scope: RUN_TIME
  value: "3001"
